### ISSUE TITLE
CMakeLists MS/TP issue

### ISSUE THREAD

**Issue by josmithua** [bacnet-stack/bacnet-stack#125]
Wondering if the CMakeLists.txt should be changed like so:

```diff
    ...
-   $<$<BOOL:${BACDL_MSTP}>:src/bacnet/datalink/mstp.h>
+   $<$<BOOL:${BACDL_MSTP}>:src/bacnet/datalink/mstp.c>
    src/bacnet/datalink/mstpdef.h
    src/bacnet/datalink/mstp.h
    ...
```

Currently if BACDL_MSTP is defined, the line will be the same as the one two lines down.

If so, I can create a PR.

**Comment by gocarlos** [comment]
yes, you are right, please provide a MR
