### ISSUE TITLE
`handler_timesync_send` will never send a time update

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [bacnet-stack/bacnet-stack#206]
It seems that the `handler_timesync_send` is non-functional - it'll never send a time update out, due to what looks like a bug: The `status` can never be true, and so the inner `Send_TimeSync_Remote` is never called.

```
#if defined(BACNET_TIME_MASTER)
static void handler_timesync_send(BACNET_DATE_TIME *current_date_time)
{
    unsigned index = 0;
    bool status = false;

    for (index = 0; index < MAX_TIME_SYNC_RECIPIENTS; index++) {
        if (Time_Sync_Recipients[index].tag == 1) {
            if (status) {
                Send_TimeSync_Remote(&Time_Sync_Recipients[index].type.address,
                    &current_date_time->date, &current_date_time->time);
            }
        }
    }
}
#endif
```

https://github.com/bacnet-stack/bacnet-stack/blob/master/src/bacnet/basic/service/h_ts.c#L162

**Comment by skarg** [comment]
fixed. Thank you, @AlexanderWells-diamond for noticing the problem and reporting it.
