### ISSUE TITLE
Compiling issues using BACDL_MSTP and BACDL_BIP

### ISSUE THREAD

**Issue by Machinegon** [bacnet-stack/bacnet-stack#240]
Hi,

I'm trying to compile and test the BACnet ms/tp router for a linux platform.
I pulled the head on the mastetr branch from the project, commit b787173a56e0fee74ad518bea7c20783ef4dcd37

The library fails to compile if I set BACDL_MSTP=ON and BACDL_BIP=ON

Trace:
`
/home/mgbolduc/code/github/bacnet-stack/src/bacnet/basic/npdu/h_routed_npdu.c: In function ‘routed_apdu_handler’:
/home/mgbolduc/code/github/bacnet-stack/src/bacnet/basic/npdu/h_routed_npdu.c:208:13: warning: implicit declaration of function ‘bvlc_get_function_code’ [-Wimplicit-function-declaration]
  208 |         if (bvlc_get_function_code() != BVLC_ORIGINAL_UNICAST_NPDU) {
      |             ^~~~~~~~~~~~~~~~~~~~~~
/home/mgbolduc/code/github/bacnet-stack/src/bacnet/basic/npdu/h_routed_npdu.c:208:41: error: BVLC_ORIGINAL_UNICAST_NPDU undeclared (first use in this function)
  208 |         if (bvlc_get_function_code() != BVLC_ORIGINAL_UNICAST_NPDU) {
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
`
Investigation:
The header file bvlc.h is missing. This is coming from the datalink.h and is not included because of this pragma block at lines 55-71:

#elif defined(BACDL_MSTP)
#include "bacnet/datalink/dlmstp.h"
#define MAX_MPDU DLMSTP_MPDU_MAX

#define datalink_init dlmstp_init
#define datalink_send_pdu dlmstp_send_pdu
#define datalink_receive dlmstp_receive
#define datalink_cleanup dlmstp_cleanup
#define datalink_get_broadcast_address dlmstp_get_broadcast_address
#define datalink_get_my_address dlmstp_get_my_address
#define datalink_maintenance_timer(s)

#elif defined(BACDL_BIP)
#include "bacnet/datalink/bip.h"
#include "bacnet/datalink/bvlc.h"
#include "bacnet/basic/bbmd/h_bbmd.h"
#define MAX_MPDU BIP_MPDU_MAX

I'm not sure why this is intended and if we can support both IP and MSTP at the same time.
The router documentation states that using both IP and MSTP is supported.

If I manually include the missing file I'm getting these worrysome warnings here:
`
/home/mgbolduc/code/github/bacnet-stack/src/bacnet/datalink/dlenv.c:97:10: warning: implicit declaration of function ‘bvlc_get_last_result’; did you mean ‘bvlc_decode_result’? [-Wimplicit-function-declaration]
   97 |         (bvlc_get_last_result() == BVLC_RESULT_REGISTER_FOREIGN_DEVICE_NAK)) {
      |          ^~~~~~~~~~~~~~~~~~~~
      |          bvlc_decode_result
/home/mgbolduc/code/github/bacnet-stack/src/bacnet/datalink/dlenv.c: In function ‘dlenv_register_as_foreign_device’:
/home/mgbolduc/code/github/bacnet-stack/src/bacnet/datalink/dlenv.c:152:30: warning: implicit declaration of function ‘bip_get_addr_by_name’ [-Wimplicit-function-declaration]
  152 |         BBMD_Address_Valid = bip_get_addr_by_name(pEnv, &BBMD_Address);
`
If I try to continue anyway I'm getting this linker error:
`
[ 72%] Linking C executable writeprop
/usr/bin/ld: libbacnet-stack.a(rs485.c.o): in function RS485_Initialize':
rs485.c:(.text+0xd99): undefined reference to round
`

If  I add the missing -lm flag to link with math and I try to run the router application, it's getting stuck infinitly at "Initializing" when I set an ms/tp port in the configuration.

> opt = c
> dev_type = bip
> dev_type = mstp
> cmd file parse success
> Initializing... 
> MS/TP Interface: 
> No such file or directory
> Interface: enp0s8
> IP Address: 192.168.56.101
> IP Broadcast Address: 192.168.56.255
> UDP Port: 0xBAC1 [47809]
> Initializing...
> Initializing...

Is there any problems here? If not, what's the correct way to get this setup.

Thank you!

**Comment by skarg** [comment]
Unfortunately, the apps/router is not cleanly built using CMake at the moment.

apps/router can be easily built on Linux using GNU Make:
```
$ make clean
$ make router
make -s -C apps router
   text	   data	    bss	    dec	    hex	filename
  52606	   2040	   4400	  59046	   e6a6	router
```
