### ISSUE TITLE
Unreachable code in bacstr.c octetstring_init_ascii_hex

### ISSUE THREAD

**Issue by rlstrand** [bacnet-stack/bacnet-stack#260]
In function octetstring_init_ascii_hex:

                if (octet_string->length <= MAX_OCTET_STRING_BYTES) {
                    octet_string->value[octet_string->length] = value;
                    octet_string->length++;
                    /* at least one pair was decoded */
                    status = true;
                } else {
                    break;
                    status = false;
                }

Got warning Pe111in IAR ARM compiler:

The "status = false" in the else clause is unreachable

**Comment by skarg** [comment]
Thank you for reporting the problem! Fixed:
https://github.com/bacnet-stack/bacnet-stack/commit/64a58d8581c29c53d37941d482df0f11d4f53620
