### ISSUE TITLE
Wrong values returned when using ReadProperty

### ISSUE THREAD

**Issue by jgiucci** [bacnet-stack/bacnet-stack#277]
Hi! 

We want to monitor devices using BACnet protocol. 

We thought that we got it working downloading the bacnet-stack into a linux virtual machine and using bacrp command, but after a couple of days we realized that the result we were getting were quite random:

![image](https://user-images.githubusercontent.com/51169290/169586610-b9b29b3a-36ef-4814-b961-8e4e2f112fcf.png)

This represents an alarm, which should always be “inactive” (mapped to value 1). The same device is being queried by another software and the values are stable, so it’s an issue from our side.

We need to check several "objects" from multiple devices from the same linux VM. In some cases it seems that the values are getting mixed up:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/51169290/169587443-14419a7d-4292-4b80-8f1f-32b8cb76872d.png">

We are quite new to bacnet so maybe we are doing something wrong. 

We appreciate any help we can get!

**Comment by skarg** [comment]
We discussed this problem off-list.  Here are the high-lights:

Me:
> Many BACnet devices have only 1 receive/transmit buffer or a single transaction limit, and therefore, can only handle a single request at a time. I suppose it could be possible to test for this case to know if the device can support more than 1 request; there isn't a property that can be read that indicates this value.

> If the device supports ReadPropertyMultiple, you could ask the device for multiple properties in a single request, up to the amount that its APDU size will allow for reply.

Joaquin replied:
> i looked at the ReadPropertyMultiple option, but I don’t know if it accepts the same parameters as ReadProperty. I didn’t see that in the documentation.
> ...
> Mac address (IP and port)
> Destination Network
> Destination Address

Me:
> I added MAC, DNET, and DADR to bacrpm today (same as bacrp - since I copied it)
> https://github.com/bacnet-stack/bacnet-stack/pull/295

Joaquin replied:
> I copied the latest version, and it works perfectly:
