### ISSUE TITLE
Cannot build port/Win32 missing file key.c

### ISSUE THREAD

**Issue by rlstrand** [bacnet-stack/bacnet-stack#316]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open source file: '..\..\..\..\src\bacnet\basic\sys\key.c': No such file or directory	BACnet_Stack_Library	C:\projects\bacnet\bacnet-stack-master\ports\win32\Microsoft Visual Studio 2019\BACnet_Stack_Library\c1	1	

I found key.c in a fork on the web and placed into ..\..\..\..\src\bacnet\basic\sys\.  The project then builds.  Is it not commited?

**Comment by skarg** [comment]
key.c only contained unit tests and was did not contain any code for the project.
