### ISSUE TITLE
missing uci_config.h & uci.h

### ISSUE THREAD

**Issue by jeff0778** [bacnet-stack/bacnet-stack#332]
When compiling its complaining about a missing include file
#include <uci_config.h>
#include <uci.h>

from the ucix.c file

I've looked for this in other folders but can't find them.

**Comment by skarg** [comment]
Please review UCI help from another issue:
[openwrt build environment](https://github.com/stargieg/bacnet-stack/issues/1#issuecomment-179958554)

**Comment by jeff0778** [comment]
thanks
