### ISSUE TITLE
All-zero BACnet IP Listening Problem

### ISSUE THREAD

**Issue by Lee-nju** [bacnet-stack/bacnet-stack#346]
This is what the source code in version bacnet-stack-v1.0.0 ports/linux/bip-init.c says, which binds ip 0.0.0.0.
![image](https://user-images.githubusercontent.com/43922456/194754353-4bc8705f-1e19-4bba-9fcf-60374e441ca8.png)

After the protocol is opened，BACnet/IP is listening ip all-zero which creates an implicit risk.
```sh
$ netstate -anp
```
![image](https://user-images.githubusercontent.com/43922456/194754506-e438fe38-e1b4-49e7-9e16-80c960d57e5f.png)

**Comment by sambabug** [comment]
Is it because the socket is already bound to another address (EINVAL)? Is this reproducible on other machines?

**Comment by skarg** [comment]
The purpose of using INADDR_ANY is to bind to all network interfaces with the specific BACnet/IP UDP port number.

See:
https://stackoverflow.com/questions/16508685/understanding-inaddr-any-for-socket-programming

> If the (sin_addr.s_addr) field is set to the constant INADDR_ANY, as defined in netinet/in.h, the caller is requesting that the socket be bound to all network interfaces on the host. Subsequently, UDP packets and TCP connections from all interfaces (which match the bound name) are routed to the application. This becomes important when a server offers a service to multiple networks. By leaving the address unspecified, the server can accept all UDP packets and TCP connection requests made for its port, regardless of the network interface on which the requests arrived.

The master branch code (soon to be 1.1.0) uses two sockets: one for unicast, and one for broadcast.

**Comment by Lee-nju** [comment]
Well, thank you for your patience, and I understand the reason for this. But when it comes to security, that's not what all users want. It is expected that unicast will be integrated in the next version.

**Comment by Lee-nju** [comment]
Let me ask you a question. For example, I have a device with multiple network ports, some of which do not want to run bacnet Ip. What can I do? Is it possible to open bip-init.c, like dlmstp_linux.c, so that developers can define their own networks?

**Comment by skarg** [comment]
The environment variable BACNET_IFACE is used to explicitly tell bip-init.c which interface to use without having to modify the code.
$ export BACNET_IFACE=eth0

**Comment by Lee-nju** [comment]
@skarg I did bind GE0 port to IFACE, but the final result was as shown in the problem description.
![image](https://user-images.githubusercontent.com/43922456/200723656-2e51ba43-c8f1-4f7a-9972-c682254db589.png)
I found that it was modified in this code.
