### ISSUE TITLE
bacnet-tools v1.0 bacserv | Tag value out of range

### ISSUE THREAD

**Issue by tblong** [bacnet-stack/bacnet-stack#398]
Using bacnet-tools v1.0 `bacserv` playing the role of the BACnet device for this question.  I'm currently dealing in the BACnet protocol revision 19 and I've not dug into whether or not unsigned int tag lengths greater than 4 are valid in this and later revisions.

**The question:** Is it by design to have `bacserv` respond with invalid application tag lengths (5+) for the unsigned int type on Accumulator instances 32 and greater? 

If the above is intentional, then I have to imagine this would for the purpose of testing the resiliency of other devices and tools?  If not, then below is a capture showing the application tag length of 5 being returned from reading ACC:33 served up by the `bacserv` application:

![image](https://user-images.githubusercontent.com/12371929/219071467-b5ca1063-0896-4904-a3d4-d677247fe6dd.png)

**Edit:**
Think I see now that ACC:33 is using an extended value tag that I've not seen before.  Perhaps this is a tag type which is not supported well by the BACnet client library I'm using; the real reason I'm asking the questions here.

**Comment by skarg** [comment]
It is by design to have the example/sample/demo/basic Accumulator object have a present-value that is 1-bit to 64-bits to see how clients respond to unsigned values larger than 32-bits.  The BACnet standard allows integer values larger than 32-bits, although some of the object property and service values are constrained.

**Comment by tblong** [comment]
Thanks much Steve, I'll close this question out.
