### ISSUE TITLE
Error Build ESP32

### ISSUE THREAD

**Issue by hongnhan100** [bacnet-stack/bacnet-stack#42]
I get an error when I build a project ..\ports\esp32.
I have followed the readme.txt but failed
libraries/bacnet/bacnet/datalink/bip.h:26:21: fatal error: bacport.h: No such file or directory
Can Team help me?

**Comment by waterfox207** [comment]
Hi,
what was the solution for this Problem? I have also bacport.h missing
`src\bacnet\basic\bbmd6\h_bbmd6.c:46:10: fatal error: bacport.h: No such file or directory`
