### ISSUE TITLE
Library stable release

### ISSUE THREAD

**Issue by IGD-james** [bacnet-stack/bacnet-stack#439]
Hi,

Which release is the latest but most stable, is master a stable branch or used for development?

I noticed the last release was 3 years ago but it is still actively maintained, should I use release 1.0.0 as the latest stable?

Thanks

**Comment by skarg** [comment]
The master branch is used for development, but should be relatively stable as we have a lot of validation occurring in continuous integration (aka github actions, or pipelines).  However, there can be bugs unintentionally introduced by changes or feature additions - feel free to submit an issue, a bug report via bacnet.sourceforge.net, or submit a fix via github.

I have been neglecting a regular release - very sorry about that.  BACnet committee meetings this June gave me some free time during the working group meetings to create a release, so version 1.1.0 is now tagged from the master branch and released and available from tags or zips from github or sourceforge.

https://sourceforge.net/projects/bacnet/files/bacnet-stack/bacnet-stack-1.1.0/

https://sourceforge.net/projects/bacnet/files/bacnet-tools/bacnet-tools-1.1.0/

https://github.com/bacnet-stack/bacnet-stack/tree/bacnet-stack-1.1
