### ISSUE TITLE
Python wrapper for BACnet/MSTP

### ISSUE THREAD

**Issue by ChristianTremblay** [bacnet-stack/bacnet-stack#44]
Hi ! I'm wondering if I could have some help from you to build a C Extension from the stack to allow Python to use MSTP.

Speed and timers being at the core of MSTP, it's very hard (let say it won't be possible) to have MSTP working in pure Python... but it would be possible as a C extension.

My C knowledge is -2 on a scale of 0 to 10... but I could help with the Python part.

[ref] https://docs.python.org/3/extending/building.html

That would be a super nice add-on to our projects.

https://github.com/ChristianTremblay/BAC0
https://github.com/JoelBender/bacpypes 

Thanks !

**Comment by ChristianTremblay** [comment]
Seems someone else made it
https://github.com/riptideio/misty

**Comment by deve87** [comment]
Is it possible to use misty directly in BAC0?
