### ISSUE TITLE
After enabling the macro definition of BACNET_SVC_SERVER, an error occurred.

### ISSUE THREAD

**Issue by Lance-He** [bacnet-stack/bacnet-stack#551]
I have enabled the macro definition of ”BACNET_SVC_SERVER“ in config.h. When compiling, it prompted an error:

h_apdu.c:(.text.apdu_handler+0x32a): undefined reference to `bacerror_decode_error_class_and_code'
collect2: error: ld returned 1 exit status

Please help me, thank you very much.

**Comment by skarg** [comment]
`BACNET_SVC_SERVER=1` was designed for compiling with PIC18 and other compilers that are unable to reduce code space using the linker, but has not been kept up to date. I've made a few changes in the files to better support that feature, and the library will build without some specific client functions when `BACNET_SVC_SERVER=1`.  However, most of the example apps/ are client apps and require the client features, so I added some `#error` in the apps to indicate that they are incompatible with that macro setting.

Do you really need to set the BACNET_SVC_SERVER for your project, or are you trying to solve a specific issue with your project and just 'pushing the buttons'?
