### ISSUE TITLE
Calendar and BACnetCalendarEntry

### ISSUE THREAD

**Issue by fabcamagna** [bacnet-stack/bacnet-stack#563]
I'm coding a Calendar Object, but I can't implement PROP_DATE_LIST and BACnetCalendarEntry,
anyone did it or could give me some advice?

**Comment by MightyPork** [comment]
Yes I still didn't get around to merging that, because it works and we are just using the branch so this doesn't get priority.

https://github.com/bacnet-stack/bacnet-stack/pull/474
