### ISSUE TITLE
Invoke ID mismatch

### ISSUE THREAD

**Issue by mczerski** [bacnet-stack/bacnet-stack#632]
Hi, I'm evaluating bacnet-stack for use in my project.
As a first step i built two bacnet master apps on linux and connected them with two usb-rs485 converters creating two node network.
Generally the communication works but sometimes I get this error:
```
DLMSTP: DER Compare failed: Invoke ID mismatch.
```
And I traced it to ports/linux/dlmstp.c:540 (version 1.3.4).

Is this something I need to worry about ? What that error means ?

**Comment by skarg** [comment]
Those printed errors in DLMSTP module should probably be changed to debug_printf() - I created a branch & pull request to do that. 

The messages get printed when the BACnet message that is at the front of the single transmit queue doesn't match the incoming Data-Expecting-Reply (DER) frame. This is often the case when an MS/TP device is performing client services. 

If the message matched, the DER frame could get an immediate reply, but often a reply takes more than the Treply_timeout to be generated. From the BACnet standard:

       The minimum time without a DataAvailable or ReceiveError event
       that a node must wait for a station to begin replying to a
       confirmed request: 255 milliseconds. (Implementations may use
       larger values for this timeout, not to exceed 300 milliseconds.)

**Comment by mczerski** [comment]
OK, that would make sense. Thanks for response. You may close the issue
