### ISSUE TITLE
Structured-View-Object

### ISSUE THREAD

**Issue by coskunyildirimcosel** [bacnet-stack/bacnet-stack#637]
Hi Steve, can you give an example for a Structured View Object?
What I want to do is to collect all the object types I have defined in a single structure.
I want to create a tree structure. For example, I want to access the analog value and binary value of a component from the tree structure. If this is possible how can I do it?
![image](https://github.com/bacnet-stack/bacnet-stack/assets/122806443/5256979b-156c-42a0-b754-70ef6dba57a9)

**Comment by cyberumut** [comment]
I need this too. Do you have any recommend ?  @skarg
