### ISSUE TITLE
apps/router need bip.o?

### ISSUE THREAD

**Issue by dmgwww** [bacnet-stack/bacnet-stack#67]
`admin@ubuntu:~/bacnet-stack/apps$ make router
make -s -b -C router
make[1]: *** No rule to make target '../../src/bacnet/datalink/bip.o', needed by 'router'.  Stop.
Makefile:278: recipe for target 'router' failed
make: *** [router] Error 2`

**Comment by skarg** [comment]
Fixed in [commit 33cc55d](https://github.com/bacnet-stack/bacnet-stack/commit/33cc55db303418ef30619a2eb7e18fc35c5d5e1d)
Added make router to Travis CI to be sure to validate build on every commit.
