### ISSUE TITLE
APDU Timeout!

### ISSUE THREAD

**Issue by ztardik** [bacnet-stack/bacnet-stack#70]
Hello,

I've built the latest source from github on Fedora 31 and trying to connect to Siemens PXC100E.D  (configured and running).

Ethernet: enp6s0 - 10.180.220.8 by DHCP
Controller: 10.180.220.6 static, BDT/FDT enabled
Firewall: off

> [zoltan@fedora bin]$ env BACNET_IFACE=enp6s0 ./bacwi -1
> Device   MAC (hex)            SNET  SADR (hex)           APDU
> -------- -------------------- ----- -------------------- ----
> 4194303 0A:B4:DC:02:BA:C0    0     00                   1476 
> 2124801 0A:B4:DC:06:BA:C0    0     00                   1476 
> 
> Total Devices: 2
> 
> [zoltan@fedora bin]$ env BACNET_IFACE=enp6s0 ./bacepics -v 2124801
> Error: APDU Timeout! (10s)
> } 
> End of BACnet Protocol Implementation Conformance Statement
>
> [zoltan@fedora bin]$ env BACNET_IFACE=enp6s0 ./bacepics -v 4194303
> Error: Unable to bind to 4194303 after waiting 10 seconds.
> Error: APDU Timeout! (11s)
>
>[zoltan@fedora bin]$ env BACNET_IFACE=enp6s0 ./bacepics -t 0A:B4:DC:06:BA:C0 -v 2124801
> Error: APDU Timeout! (10s)
> } 
> End of BACnet Protocol Implementation Conformance Statement
> 
> [zoltan@fedora bin]$ env BACNET_IFACE=enp6s0 ./bacepics -t 0A:B4:DC:02:BA:C0 -v 4194303
> Error: APDU Timeout! (10s)
> } 
> End of BACnet Protocol Implementation Conformance Statement
> 

What should I do to get the communication working? My understanding is that this should work out of box, if compile was successful.
I have no clue what is the 4194303 device,  only one Bacnet device is on the network. 

Thanks

**Comment by skarg** [comment]
Thank you for reporting the problem!  I made an error in the BACnet/IPv4 decoder when I refactored the BACnet/IPv4 handling.  Although I tested the BACnet/IPv4 initially with non-BBMD, I tested last with Foreign Device Registration and BBMD, and must not have gone back and re-tested without BBMD.
