### ISSUE TITLE
mstpcap considers valid frames as invalid if used as a standalone tool

### ISSUE THREAD

**Issue by nazaryev-cool** [bacnet-stack/bacnet-stack#811]
My setup: Linux PC + mstpcap (run as `./mstpcap /dev/ttyUSB0`) + USB-RS485 + only one certified MSTP master (KMC Controls BAC-4000) on the bus and it sends only PFM frames.

What I get with the latest build based on master branch:
```
RS485 Interface: /dev/ttyUSB0
RS485 Baud Rate 38400
mstpcap: Using /dev/ttyUSB0 for capture at 38400 bps.
mstpcap: saving capture to mstp_20241015153954.cap
0 packets, 48 invalid frames
```

What I get with commit 9e0751f8c9ced0e047bd4cc9c3282f52e417bf9f:
```
RS485 Interface: /dev/ttyUSB0
RS485 Baud Rate 38400
mstpcap: Using /dev/ttyUSB0 for capture at 38400 bps.
mstpcap: saving capture to mstp_20241015154219.cap
100 packets, 0 invalid frames
```

Commit that breaks the functionality: ddb2b4312533cfc7f94e83ce3290fe4e7cabac00

As far as I understand the issue lays somewhere [here](https://github.com/bacnet-stack/bacnet-stack/commit/ddb2b4312533cfc7f94e83ce3290fe4e7cabac00#diff-1588ab63cc895450b3109303e461f1ff6019d308e2e45852c711527479899fd7L455) (or [here](https://github.com/bacnet-stack/bacnet-stack/blob/2b58f5b122110b34c82282bd3cc2060c8719cd21/src/bacnet/datalink/mstp.c#L432) in master branch) as the new code does not take into account mstpcap use-case.

**Comment by skarg** [comment]
Thank you for reporting the problem and bisecting where the issue appeared.

I modified the MS/TP receive state machine for zero-configuration MAC proposal which uses TS (this station) = 255 for promiscuous mode to monitor packets, and the mstpcap code was still using TS=127.
