### ISSUE TITLE
IS network number in BACnet IP server sample code support?

### ISSUE THREAD

**Issue by monexiao** [bacnet-stack/bacnet-stack#85]
We has a project need the device use BACnet IP to provide data to controller, and the network number features might be required. Is the feature is worked in this stack library? We use the https://sourceforge.net/projects/bacnet/ before, but the feature does not seem to support.

**Comment by skarg** [comment]
The [basic NPDU handler](https://github.com/bacnet-stack/bacnet-stack/blob/master/src/bacnet/basic/npdu/h_npdu.c) includes support for What-Is-Network-Number and Network-Number-Is services.  There is also a sample app (bacnni)  that sends Network-Number-Is and a sample app (bacwinn) that sends What-Is-Network-Number for assisting the validation of the network messages.

The BACnet stack library project at github.com is sync'd with the BACnet stack library at sourceforge.net project.
